fix(www): make sure state is set on location (showcase) (#11144)
Fixes
```
  145 |               state={{
  146 |                 isModal: true,
> 147 |                 filters: parent.props.location.state.filters,
      |                                                      ^
  148 |               }}
  149 |               css={{
  150 |                 display: `block`
```
  WebpackError: TypeError: Cannot read property 'filters' of undefined